USE desarrollo;
DROP TABLE DBO.DTOESTUDIANTE;

BEGIN TRANSACTION
GO
CREATE TABLE  dbo.DTOESTUDIANTE
	(IDALUMNO INT IDENTITY (1,1) NOT NULL,
	VNOMBRE VARCHAR(50) NOT NULL,
	VAPATERNO VARCHAR(50) NOT NULL,
	VAMATERNO VARCHAR(50) NOT NULL,
	DNACIMIENTO DATE NOT NULL,
	VMATRICULA AS ('1' + REPLICATE('0',5-LEN(IDALUMNO)) + CAST(IDALUMNO AS INT)) PERSISTED,
	VSTATUS VARCHAR(2) NOT NULL) ON[PRIMARY]
COMMIT

/*-TEST-*/
INSERT INTO DTOESTUDIANTE(VNOMBRE,VAPATERNO,VAMATERNO,DNACIMIENTO,VSTATUS) VALUES('SALVADOR','HERNANDEZ','ROMAN','1991-07-20','A')

/*INSERTA*/
ALTER PROCEDURE SPINS_ESTUDIANTE(@VNOMBRE varchar(50), 
                    @VAPATERNO varchar(50),
                    @VAMATERNO varchar(50),
                    @DNACIMIENTO date,
                    @VSTATUS varchar(10))
AS 
BEGIN
    SET NOCOUNT ON;
    INSERT INTO DTOESTUDIANTE ([VNOMBRE],[VAPATERNO],[VAMATERNO],[DNACIMIENTO],[VSTATUS])
                    values (@VNOMBRE,@VAPATERNO,@VAMATERNO,@DNACIMIENTO,@VSTATUS)
    SELECT TOP 1 * FROM DTOESTUDIANTE
                WHERE VNOMBRE = @VNOMBRE
                AND VAPATERNO = @VAPATERNO AND VAMATERNO = @VAMATERNO
                AND DNACIMIENTO = @DNACIMIENTO ORDER BY IDALUMNO DESC
END;
 
/*ELIMINA*/
ALTER PROCEDURE SPDEL_ESTUDIANTE(@UNICO INTEGER,
                    @DNACIMIENTO DATE)
AS
BEGIN
    DELETE FROM DTOESTUDIANTE WHERE VMATRICULA = @UNICO AND DNACIMIENTO = @DNACIMIENTO;
    PRINT 'COMPLETADO';
END;
 
 
/*BUSQUEDA*/
ALTER PROCEDURE SPFIND_ESTUDIANTE(@VMATRICULA INTEGER)
AS
BEGIN
    SELECT * FROM DTOESTUDIANTE WHERE VMATRICULA = @VMATRICULA
END; 
 
/*ACTUALIZA*/
ALTER PROCEDURE SPUPD_ESTUDIANTE(@VNOMBRE varchar(50), 
                    @VAPATERNO varchar(50),
                    @VAMATERNO varchar(50),
                    @DNACIMIENTO date,
                    @VSTATUS varchar(10),
                    @VMATRICULA INTEGER)
AS
BEGIN
    UPDATE DTOESTUDIANTE 
        SET VNOMBRE = @VNOMBRE, VAPATERNO = @VAPATERNO, VAMATERNO = @VAMATERNO, DNACIMIENTO = @DNACIMIENTO, VSTATUS = @VSTATUS 
        WHERE VMATRICULA = @VMATRICULA;
    SELECT * FROM DTOESTUDIANTE WHERE VMATRICULA = @VMATRICULA;
END;
 
SELECT * FROM DTOESTUDIANTE
EXEC SPINS_ESTUDIANTE 'JUAN','JUAREZ','BALLESTEROS','1985-10-14','A'
EXEC SPDEL_ESTUDIANTE 1013, '1991-07-20'
EXEC SPFIND_ESTUDIANTE 10003
EXEC SPUPD_ESTUDIANTE 'JAVIER','GALVAN','HERRERA','1993-11-14','B', 10006
